# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/video
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/video/720cee1a-734b-4e88-8354-b5e129332449/transcription
Content-Type: application/json

{
   "prompt": "Tailwind, Prettier, ESLint"
}

###

# @name generate
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
   "videoId": "ce2e55a5-9599-47a6-b3c0-bfd98be43745",
   "temperature": 0.5,
   "prompt": "Gere um resumo sucinto da transcriçao do video informada a seguir: '''{transcription}'''"
}